/** Re-export plan helpers for Electron main (shared with renderer via src/utils). */
export {
  applyCheckpoint,
  applyUpdateTodo,
  assistantImpliesPendingFileChanges,
  COARSE_PLAN_ACTIVE_TODO_MAX,
  countActiveTodos,
  countOpenTodos,
  createAgentPlanState,
  formatAgentPlanForModel,
  formatCoarseTodoPlanNudge,
  formatInitialTodoPlanNudge,
  formatMissingProposeActionsNudge,
  formatOpenTodosNudge,
  formatTodosList,
  formatTruncatedProposeActionsNudge,
  getOpenTodos,
  looksLikeMultiPartAgentTask,
  looksLikeWorkspaceChangeRequest,
  rebuildPlanFromSteps,
  sanitizeCheckpointArgs,
  sanitizeUpdateTodoArgs,
  collectAgentStepsThrough,
  shouldNudgeCoarseTodoPlan,
  shouldNudgeMissingProposeActions,
  shouldNudgeMissingTodoPlan,
  shouldPlanFirstAgentTask,
  shouldShowAgentPlanPanel,
  looksLikeVaguePhaseTodo,
  shouldHintCoarseAgentPlan,
  type AgentPlanState,
  type AgentTodoItem,
  type AgentTodoStatus
} from '../../src/utils/agent-plan'
